name: cs442_mp1
description: CS 442 MP1 - Profile information page
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  flutter_blurhash: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/vijay.jpeg
    - assets/images/samrthomes.svg
    - assets/images/homehub.svg
    - assets/images/sofa and chill.svg
    - assets/images/sarjani.svg
    - assets/images/Marwiz.svg